// GrowthPage Constants
import type { 
  GrowthRoutine, 
  GrowthGoal, 
  PersonalResource,
  ProfessionalProject,
  PsycheResource,
  MentalCard,
  SpiritualityPractice,
  GrowthCategory,
  HabitCategory
} from './types';
import { 
  Sun, Moon, Brain, Target, TrendingUp, Users, DollarSign, 
  BookOpen, Video, Headphones, FileText, Zap, Heart, Star,
  Lightbulb, Rocket, Briefcase, TrendingDown, Clock, Calendar
} from 'lucide-react';

// ============================================
// CATEGORIES
// ============================================

export const growthCategories: { id: GrowthCategory; label: string; icon: string; color: string }[] = [
  { id: 'health', label: 'Santé', icon: '❤️', color: '#ef4444' },
  { id: 'mind', label: 'Esprit', icon: '🧠', color: '#8b5cf6' },
  { id: 'productivity', label: 'Productivité', icon: '⚡', color: '#f59e0b' },
  { id: 'learning', label: 'Apprentissage', icon: '📚', color: '#3b82f6' },
  { id: 'relationships', label: 'Relations', icon: '👥', color: '#ec4899' },
  { id: 'finance', label: 'Finance', icon: '💰', color: '#10b981' },
  { id: 'spirit', label: 'Spiritualité', icon: '✨', color: '#6366f1' },
  { id: 'creativity', label: 'Créativité', icon: '🎨', color: '#f97316' },
  { id: 'professional', label: 'Professionnel', icon: '💼', color: '#64748b' },
];

// ============================================
// SECTION 1: ROUTINES & GOALS
// ============================================

export const initialRoutines: GrowthRoutine[] = [
  {
    id: 'routine-1',
    title: 'Routine Morning 5AM',
    description: 'Le pouvoir des 5 heures du matin pour conquérir sa journée',
    category: 'morning',
    frequency: 'daily',
    daysOfWeek: [1, 2, 3, 4, 5],
    timeOfDay: '05:00',
    duration: 60,
    isActive: true,
    currentStreak: 12,
    bestStreak: 45,
    totalCompletions: 156,
    icon: '🌅',
    color: '#f59e0b',
    steps: [
      { id: 's1', title: 'Hydratation', description: 'Boire 500ml d\'eau', duration: 2, order: 0, isCompleted: false },
      { id: 's2', title: 'Méditation', description: '15 min de méditation silencieuse', duration: 15, order: 1, isCompleted: false },
      { id: 's3', title: 'Journaling', description: 'Écrire 3 pages de réflexions', duration: 20, order: 2, isCompleted: false },
      { id: 's4', title: 'Exercice', description: '30 min d\'exercice physique', duration: 30, order: 3, isCompleted: false },
    ],
  },
  {
    id: 'routine-2',
    title: 'Routine Evening Wind-Down',
    description: 'Déconnecter et préparer un sommeil réparateur',
    category: 'evening',
    frequency: 'daily',
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: '21:30',
    duration: 45,
    isActive: true,
    currentStreak: 8,
    bestStreak: 30,
    totalCompletions: 89,
    icon: '🌙',
    color: '#6366f1',
    steps: [
      { id: 's1', title: 'Review journée', description: 'Noter 3 victoires et 1 leçon', duration: 10, order: 0, isCompleted: false },
      { id: 's2', title: 'Gratitude', description: 'Écrire 3 choses reconnaissantes', duration: 5, order: 1, isCompleted: false },
      { id: 's3', title: 'Lecture', description: '20 min de lecture inspirante', duration: 20, order: 2, isCompleted: false },
      { id: 's4', title: 'Digital Detox', description: 'Écrans éteints, préparation sommeil', duration: 10, order: 3, isCompleted: false },
    ],
  },
  {
    id: 'routine-3',
    title: 'Weekly Review',
    description: 'Bilan hebdomadaire et planification',
    category: 'custom',
    frequency: 'weekly',
    daysOfWeek: [0],
    timeOfDay: '10:00',
    duration: 90,
    isActive: true,
    currentStreak: 4,
    bestStreak: 12,
    totalCompletions: 32,
    icon: '📊',
    color: '#10b981',
    steps: [
      { id: 's1', title: 'Review objectifs', description: 'Vérifier progression objectifs', duration: 20, order: 0, isCompleted: false },
      { id: 's2', title: 'Analyse semaine', description: 'Qu\'est-ce qui a fonctionné ?', duration: 20, order: 1, isCompleted: false },
      { id: 's3', title: 'Planification', description: 'Définir priorités semaine suivante', duration: 30, order: 2, isCompleted: false },
      { id: 's4', title: 'Calendrier', description: 'Bloquer temps pour l\'important', duration: 20, order: 3, isCompleted: false },
    ],
  },
];

export const initialGoals: GrowthGoal[] = [
  {
    id: 'goal-1',
    title: 'Lire 52 livres cette année',
    description: 'Un livre par semaine pour élargir mes horizons',
    category: 'learning',
    type: 'outcome',
    philosophy: 'atomic',
    targetValue: 52,
    currentValue: 18,
    unit: 'livres',
    status: 'active',
    progress: 35,
    milestones: [
      { id: 'm1', title: '10 livres', completed: true, order: 0 },
      { id: 'm2', title: '25 livres', completed: false, order: 1 },
      { id: 'm3', title: '40 livres', completed: false, order: 2 },
      { id: 'm4', title: '52 livres', completed: false, order: 3 },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'goal-2',
    title: 'Méditation quotidienne',
    description: '100 jours consécutifs de méditation',
    category: 'mind',
    type: 'process',
    philosophy: 'compound',
    targetValue: 100,
    currentValue: 45,
    unit: 'jours',
    identityStatement: 'Je suis une personne qui médite chaque jour',
    status: 'active',
    progress: 45,
    milestones: [
      { id: 'm1', title: '7 jours', completed: true, order: 0 },
      { id: 'm2', title: '21 jours (habitude)', completed: true, order: 1 },
      { id: 'm3', title: '50 jours', completed: false, order: 2 },
      { id: 'm4', title: '100 jours', completed: false, order: 3 },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'goal-3',
    title: 'Mastering Japanese N3',
    description: 'Atteindre le niveau N3 en japonais',
    category: 'learning',
    type: 'outcome',
    philosophy: 'atomic',
    targetValue: 100,
    currentValue: 35,
    unit: '%',
    status: 'active',
    progress: 35,
    milestones: [
      { id: 'm1', title: 'Hiragana/Katakana', completed: true, order: 0 },
      { id: 'm2', title: 'Kanji N5', completed: true, order: 1 },
      { id: 'm3', title: 'Grammaire N4', completed: false, order: 2 },
      { id: 'm4', title: 'Kanji N4', completed: false, order: 3 },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================
// SECTION 2: PERSONAL DEVELOPMENT RESOURCES
// ============================================

export const personalResources: PersonalResource[] = [
  // BOOKS - Using OpenLibrary covers (reliable)
  {
    id: 'book-1',
    title: 'Atomic Habits',
    author: 'James Clear',
    type: 'book',
    status: 'completed',
    category: 'productivity',
    imageUrl: 'https://covers.openlibrary.org/b/id/10524325-L.jpg',
    url: 'https://openlibrary.org/works/OL28420875W/Atomic_Habits',
    description: 'Comment créer de bonnes habitudes et briser les mauvaises',
    rating: 5,
    progress: 100,
    tags: ['habitudes', 'productivité', 'changement'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'book-2',
    title: 'The Compound Effect',
    author: 'Darren Hardy',
    type: 'book',
    status: 'reading',
    category: 'mindset',
    imageUrl: 'https://covers.openlibrary.org/b/id/8225261-L.jpg',
    url: 'https://openlibrary.org/works/OL26849225W/The_Compound_Effect',
    description: 'L\'effet cumulé des petites décisions quotidiennes',
    rating: 4,
    progress: 65,
    tags: ['mindset', 'succès', 'croissance'],
    createdAt: new Date(),
  },
  {
    id: 'book-3',
    title: 'Deep Work',
    author: 'Cal Newport',
    type: 'book',
    status: 'to-read',
    category: 'productivity',
    imageUrl: 'https://covers.openlibrary.org/b/id/9908805-L.jpg',
    url: 'https://openlibrary.org/works/OL3566014W/Deep_Work',
    description: 'Règles pour un succès concentré dans un monde distrait',
    progress: 0,
    tags: ['focus', 'productivité', 'travail'],
    createdAt: new Date(),
  },
  {
    id: 'book-4',
    title: 'The 5AM Club',
    author: 'Robin Sharma',
    type: 'book',
    status: 'completed',
    category: 'mindset',
    imageUrl: 'https://covers.openlibrary.org/b/id/20460269-L.jpg',
    url: 'https://openlibrary.org/works/OL20191547W/The_5_AM_Club',
    description: 'Comment posséder ta matinée et ta vie',
    rating: 4,
    progress: 100,
    tags: ['matin', 'routine', 'succès'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'book-5',
    title: 'Mindset',
    author: 'Carol Dweck',
    type: 'book',
    status: 'to-read',
    category: 'mindset',
    imageUrl: 'https://covers.openlibrary.org/b/id/8589251-L.jpg',
    url: 'https://openlibrary.org/works/OL3392632W/Mindset',
    description: 'Comment changer votre état d\'esprit pour réussir',
    progress: 0,
    tags: ['psychologie', 'mentalité', 'croissance'],
    createdAt: new Date(),
  },
  // VIDEOS - YouTube avec IDs VALIDES (testés et fonctionnels)
  {
    id: 'video-1',
    title: 'Try Something New for 30 Days',
    author: 'Matt Cutts',
    type: 'video',
    status: 'completed',
    category: 'productivity',
    url: 'https://www.youtube.com/watch?v=UNP03fDSj1U',
    imageUrl: 'https://img.youtube.com/vi/UNP03fDSj1U/hqdefault.jpg',
    description: 'TED Talk - Créer de nouvelles habitudes en 30 jours',
    rating: 5,
    progress: 100,
    tags: ['habitudes', 'TED', 'défi'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'video-2',
    title: 'Inside the Mind of a Master Procrastinator',
    author: 'Tim Urban',
    type: 'video',
    status: 'completed',
    category: 'productivity',
    url: 'https://www.youtube.com/watch?v=arj7oStGLkU',
    imageUrl: 'https://img.youtube.com/vi/arj7oStGLkU/hqdefault.jpg',
    description: 'Comprendre le cerveau du procrastinateur - TED Talk culte',
    rating: 5,
    progress: 100,
    tags: ['procrastination', 'TED', 'productivité'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'video-3',
    title: 'The Power of Believing You Can Improve',
    author: 'Carol Dweck',
    type: 'video',
    status: 'to-watch',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=hiiEeMN7vbQ',
    imageUrl: 'https://img.youtube.com/vi/hiiEeMN7vbQ/hqdefault.jpg',
    description: 'Carol Dweck explique le mindset de croissance',
    progress: 0,
    tags: ['mindset', 'TED', 'croissance'],
    createdAt: new Date(),
  },
  {
    id: 'video-4',
    title: 'How Great Leaders Inspire Action',
    author: 'Simon Sinek',
    type: 'video',
    status: 'to-watch',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=qp0HIF3SfI4',
    imageUrl: 'https://img.youtube.com/vi/qp0HIF3SfI4/hqdefault.jpg',
    description: 'Le célèbre "Start With Why" de Simon Sinek',
    progress: 0,
    tags: ['leadership', 'TED', 'inspiration'],
    createdAt: new Date(),
  },
  {
    id: 'video-5',
    title: 'Your Body Language May Shape Who You Are',
    author: 'Amy Cuddy',
    type: 'video',
    status: 'to-watch',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=Ks-_Mh1QhMc',
    imageUrl: 'https://img.youtube.com/vi/Ks-_Mh1QhMc/hqdefault.jpg',
    description: 'Comment votre langage corporel influence votre confiance',
    progress: 0,
    tags: ['confiance', 'TED', 'psychologie'],
    createdAt: new Date(),
  },
  // ARTICLES
  {
    id: 'article-1',
    title: 'The Ultimate Guide to Personal Development',
    author: 'Scott Young',
    type: 'article',
    status: 'reading',
    category: 'mindset',
    url: 'https://www.scotthyoung.com/',
    description: 'Guide complet pour le développement personnel',
    progress: 40,
    tags: ['guide', 'développement', 'apprentissage'],
    createdAt: new Date(),
  },
  // AUDIO - Clips YouTube officiels (IDs valides)
  {
    id: 'audio-1',
    title: 'The Logical Song',
    author: 'Supertramp',
    type: 'audio',
    status: 'completed',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=kVQTb59Vz2A',
    imageUrl: 'https://img.youtube.com/vi/kVQTb59Vz2A/hqdefault.jpg',
    description: 'Réflexion sur l\'identité et la perte de soi - Classic Rock',
    rating: 5,
    progress: 100,
    tags: ['rock', 'réflexion', 'identité'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'audio-2',
    title: 'Breakfast in America',
    author: 'Supertramp',
    type: 'audio',
    status: 'completed',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=rervViPD0aM',
    imageUrl: 'https://img.youtube.com/vi/rervViPD0aM/hqdefault.jpg',
    description: 'Vision satirique du rêve américain - Classic Rock',
    rating: 5,
    progress: 100,
    tags: ['rock', 'société', 'rêve'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'audio-3',
    title: 'Africa',
    author: 'Toto',
    type: 'audio',
    status: 'completed',
    category: 'spirituality',
    url: 'https://www.youtube.com/watch?v=FTQbiNvZqaY',
    imageUrl: 'https://img.youtube.com/vi/FTQbiNvZqaY/hqdefault.jpg',
    description: 'Appel à l\'aventure et connexion avec la nature',
    rating: 5,
    progress: 100,
    tags: ['rock', 'aventure', 'nature'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'audio-4',
    title: 'Rosanna',
    author: 'Toto',
    type: 'audio',
    status: 'to-listen',
    category: 'relationships',
    url: 'https://www.youtube.com/watch?v=qgCFVvdYwss',
    imageUrl: 'https://img.youtube.com/vi/qgCFVvdYwss/hqdefault.jpg',
    description: 'L\'une des plus grandes chansons d\'amour en rock',
    rating: 5,
    progress: 0,
    tags: ['rock', 'amour', 'classique'],
    createdAt: new Date(),
  },
  {
    id: 'audio-5',
    title: 'Piano Man',
    author: 'Billy Joel',
    type: 'audio',
    status: 'completed',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=gxEPV4kolz0',
    imageUrl: 'https://img.youtube.com/vi/gxEPV4kolz0/hqdefault.jpg',
    description: 'L\'histoire d\'un pianiste de bar et de ceux qui rêvent d\'une autre vie',
    rating: 5,
    progress: 100,
    tags: ['piano', 'rêve', 'vie'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'audio-6',
    title: 'Vienna',
    author: 'Billy Joel',
    type: 'audio',
    status: 'completed',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=pDbd2vHC_5k',
    imageUrl: 'https://img.youtube.com/vi/pDbd2vHC_5k/hqdefault.jpg',
    description: 'Ralentir, prendre son temps - Vienna attend',
    rating: 5,
    progress: 100,
    tags: ['piano', 'patience', 'sagesse'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'audio-7',
    title: 'Je l\'aime à mourir',
    author: 'Francis Cabrel',
    type: 'audio',
    status: 'completed',
    category: 'relationships',
    url: 'https://www.youtube.com/watch?v=H7vUks7lVqg',
    imageUrl: 'https://img.youtube.com/vi/H7vUks7lVqg/hqdefault.jpg',
    description: 'Déclaration d\'amour intense et passionnée',
    rating: 5,
    progress: 100,
    tags: ['french', 'amour', 'passion'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'audio-8',
    title: 'La Corrida',
    author: 'Francis Cabrel',
    type: 'audio',
    status: 'to-listen',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=6H1wGMK_tLE',
    imageUrl: 'https://img.youtube.com/vi/6H1wGMK_tLE/hqdefault.jpg',
    description: 'Métaphore de la vie comme une corrid',
    rating: 4,
    progress: 0,
    tags: ['french', 'vie', 'métaphore'],
    createdAt: new Date(),
  },
  {
    id: 'audio-9',
    title: 'Sultans of Swing',
    author: 'Dire Straits',
    type: 'audio',
    status: 'completed',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=0fAQhSRLQnM',
    imageUrl: 'https://img.youtube.com/vi/0fAQhSRLQnM/hqdefault.jpg',
    description: 'Légendaire solo de guitare - Mark Knopfler au sommet',
    rating: 5,
    progress: 100,
    tags: ['rock', 'guitare', 'légende'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'audio-10',
    title: 'Money for Nothing',
    author: 'Dire Straits',
    type: 'audio',
    status: 'to-listen',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=iwDlgJA62Lc',
    imageUrl: 'https://img.youtube.com/vi/iwDlgJA62Lc/hqdefault.jpg',
    description: 'Satire du rock business et de la télévision',
    rating: 5,
    progress: 0,
    tags: ['rock', 'satire', 'classique'],
    createdAt: new Date(),
  },
  {
    id: 'audio-11',
    title: 'Brothers in Arms',
    author: 'Dire Straits',
    type: 'audio',
    status: 'to-listen',
    category: 'spirituality',
    url: 'https://www.youtube.com/watch?v=jHDsoJs0MRw',
    imageUrl: 'https://img.youtube.com/vi/jHDsoJs0MRw/hqdefault.jpg',
    description: 'Hymne pacifiste empreint de mélancolie',
    rating: 5,
    progress: 0,
    tags: ['rock', 'paix', 'émotion'],
    createdAt: new Date(),
  },
  {
    id: 'audio-12',
    title: 'House of the Rising Sun',
    author: 'The Animals',
    type: 'audio',
    status: 'completed',
    category: 'mindset',
    url: 'https://www.youtube.com/watch?v=4-43l6aq3WM',
    imageUrl: 'https://img.youtube.com/vi/4-43l6aq3WM/hqdefault.jpg',
    description: 'Classique intemporel du rock des années 60',
    rating: 5,
    progress: 100,
    tags: ['rock', 'classique', 'blues'],
    createdAt: new Date(),
    completedAt: new Date(),
  },
  {
    id: 'audio-13',
    title: 'Don\'t Let Me Be Misunderstood',
    author: 'The Animals',
    type: 'audio',
    status: 'to-listen',
    category: 'relationships',
    url: 'https://www.youtube.com/watch?v=Bw7LUEqnzws',
    imageUrl: 'https://img.youtube.com/vi/Bw7LUEqnzws/hqdefault.jpg',
    description: 'Plaidoyer pour être compris dans un monde complexe',
    rating: 4,
    progress: 0,
    tags: ['rock', 'compréhension', 'blues'],
    createdAt: new Date(),
  },
];

// ============================================
// SECTION 3: PROFESSIONAL DEVELOPMENT
// ============================================

export const professionalProjects: ProfessionalProject[] = [
  {
    id: 'proj-1',
    title: 'MindLife App',
    description: 'Application de gestion de vie personnelle',
    type: 'business',
    status: 'active',
    progress: 45,
    priority: 'high',
    startDate: new Date(),
    budget: 5000,
    spent: 1200,
    tags: ['app', 'productivité', 'SaaS'],
  },
  {
    id: 'proj-2',
    title: 'Formation React Avancé',
    description: 'Développer mes compétences en React',
    type: 'skill',
    status: 'active',
    progress: 60,
    priority: 'medium',
    tags: ['formation', 'développement', 'React'],
  },
  {
    id: 'proj-3',
    title: 'Investissement Crypto',
    description: 'Portefeuille crypto diversifié',
    type: 'investment',
    status: 'active',
    progress: 30,
    priority: 'low',
    budget: 2000,
    spent: 1500,
    roi: 12,
    tags: ['investissement', 'crypto', 'finance'],
  },
];

// ============================================
// SECTION 4: PSYCHE DEVELOPMENT
// ============================================

export const psycheResources: PsycheResource[] = [
  // NEVILLE GODDARD - Livres
  {
    id: 'psyche-1',
    title: 'Le Pouvoir de l\'Imagination',
    author: 'Neville Goddard',
    type: 'book',
    source: 'neville-goddard',
    imageUrl: 'https://covers.openlibrary.org/b/id/8521545-L.jpg',
    description: 'Maîtriser l\'art de créer sa réalité par l\'imagination',
    status: 'exploring',
    keyConcepts: ['Imagination créatrice', 'État désiré', 'Sentiment de réalité'],
    notes: 'La clé est de ressentir l\'état désiré comme déjà accompli',
  },
  {
    id: 'psyche-2',
    title: 'Feeling is the Secret',
    author: 'Neville Goddard',
    type: 'book',
    source: 'neville-goddard',
    imageUrl: 'https://covers.openlibrary.org/b/id/10523359-L.jpg',
    description: 'Le sentiment est le secret de la manifestation',
    status: 'exploring',
    keyConcepts: ['Sentiment', 'Conscience', 'Loi de l\'assomption'],
  },
  // CARL JUNG
  {
    id: 'psyche-3',
    title: 'L\'Homme et ses Symboles',
    author: 'Carl Jung',
    type: 'book',
    source: 'carl-jung',
    imageUrl: 'https://covers.openlibrary.org/b/id/8563211-L.jpg',
    description: 'Introduction à la psychologie analytique',
    status: 'exploring',
    keyConcepts: ['Inconscient collectif', 'Archétypes', 'Symboles'],
    notes: 'Explorer les symboles qui apparaissent dans mes rêves',
  },
  {
    id: 'psyche-4',
    title: 'Psychologie de l\'Inconscient',
    author: 'Carl Jung',
    type: 'book',
    source: 'carl-jung',
    imageUrl: 'https://covers.openlibrary.org/b/id/6622912-L.jpg',
    description: 'Les fondements de la psychologie analytique',
    status: 'to-explore',
    keyConcepts: ['Inconscient', 'Libido', 'Transformation'],
  },
  // HERMÈS TRISMÉGISTE
  {
    id: 'psyche-5',
    title: 'La Table d\'Émeraude',
    author: 'Hermès Trismégiste',
    type: 'book',
    source: 'hermes',
    imageUrl: 'https://covers.openlibrary.org/b/id/7741981-L.jpg',
    description: 'Les fondements de l\'alchimie spirituelle',
    status: 'integrated',
    keyConcepts: ['Comme en haut, ainsi en bas', 'Transmutation', 'Unicité'],
    rating: 5,
    notes: 'Principe de correspondance à méditer quotidiennement',
  },
  {
    id: 'psyche-6',
    title: 'Le Kybalion',
    author: 'Trois Initiés',
    type: 'book',
    source: 'hermes',
    imageUrl: 'https://covers.openlibrary.org/b/id/7619801-L.jpg',
    description: 'Les 7 principes hermétiques de la sagesse ancienne',
    status: 'exploring',
    keyConcepts: ['Mentalisme', 'Correspondance', 'Vibration'],
  },
  // VIDÉOS SPIRITUALITÉ - TED Talks valides
  {
    id: 'psyche-video-1',
    title: 'The Surprising Science of Happiness',
    author: 'Dan Gilbert',
    type: 'video',
    source: 'synchronicity',
    url: 'https://www.youtube.com/watch?v=fLJsdqxnZb0',
    imageUrl: 'https://img.youtube.com/vi/fLJsdqxnZb0/hqdefault.jpg',
    description: 'La science du bonheur et de la satisfaction',
    status: 'to-explore',
    keyConcepts: ['Bonheur', 'Satisfaction', 'Psychologie'],
  },
  {
    id: 'psyche-video-2',
    title: 'How to Speak So That People Want to Listen',
    author: 'Julian Treasure',
    type: 'video',
    source: 'synchronicity',
    url: 'https://www.youtube.com/watch?v=8jPQjjsBbIc',
    imageUrl: 'https://img.youtube.com/vi/8jPQjjsBbIc/hqdefault.jpg',
    description: 'L\'art de communiquer efficacement',
    status: 'to-explore',
    keyConcepts: ['Communication', 'Écoute', 'Influence'],
  },
];

export const mentalCards: MentalCard[] = [
  {
    id: 'card-1',
    front: 'Qu\'est-ce que l\'État Désiré selon Neville ?',
    back: 'C\'est l\'état de conscience où l\'on ressent déjà la réalisation de son désir. La clé n\'est pas de vouloir, mais d\'ÊTRE.',
    category: 'concept',
    source: 'Neville Goddard',
    masteryLevel: 75,
    reviewCount: 8,
  },
  {
    id: 'card-2',
    front: 'Que signifie "Comme en haut, ainsi en bas" ?',
    back: 'Principe hermétique de correspondance : ce qui se passe dans les plans supérieurs se reflète dans les plans inférieurs, et vice versa.',
    category: 'concept',
    source: 'Hermès Trismégiste',
    masteryLevel: 60,
    reviewCount: 5,
  },
  {
    id: 'card-3',
    front: 'Qu\'est-ce que l\'Inconscient Collectif ?',
    back: 'Selon Jung, c\'est la partie de l\'inconscient partagée par tous les humains, contenant les archétypes et symboles universels.',
    category: 'concept',
    source: 'Carl Jung',
    masteryLevel: 45,
    reviewCount: 3,
  },
  {
    id: 'card-4',
    front: 'Technique de la Révision (Neville)',
    back: 'Revoir un événement passé dans l\'imagination et le réécrire comme on l\'aurait souhaité. Cela reprogramme le subconscient.',
    category: 'practice',
    source: 'Neville Goddard',
    masteryLevel: 50,
    reviewCount: 4,
  },
  {
    id: 'card-5',
    front: '"Le sentiment est le secret"',
    back: 'Ce n\'est pas la pensée mais le SENTIMENT qui manifeste. Ressentir la réalité du désir accompli est la clé.',
    category: 'quote',
    source: 'Neville Goddard',
    masteryLevel: 80,
    reviewCount: 12,
  },
];

export const spiritualityPractices: SpiritualityPractice[] = [
  {
    id: 'practice-1',
    title: 'SATS - State Akin To Sleep',
    description: 'Technique de Neville pour programmer le subconscient',
    tradition: 'neville',
    duration: 15,
    frequency: 'Quotidienne, avant de dormir',
    instructions: [
      'Se détendre profondément dans un état de somnolence',
      'Visualiser une scène qui implique la réalisation du désir',
      'Ressentir l\'émotion de l\'accomplissement',
      'Maintenir ce sentiment en s\'endormant',
    ],
    benefits: ['Reprogramme le subconscient', 'Manifestation accélérée', 'Sommeil réparateur'],
    isFavorite: true,
  },
  {
    id: 'practice-2',
    title: 'Travail des Rêves',
    description: 'Analyse jungienne des rêves',
    tradition: 'jungian',
    duration: 30,
    frequency: 'Au réveil',
    instructions: [
      'Noter les rêves immédiatement au réveil',
      'Identifier les symboles et émotions',
      'Explorer les associations personnelles',
      'Identifier le message de l\'inconscient',
    ],
    benefits: ['Accès à l\'inconscient', 'Guidance intérieure', 'Intégration psychique'],
    isFavorite: false,
  },
  {
    id: 'practice-3',
    title: 'Méditation Hermétique',
    description: 'Contemplation des 7 principes hermétiques',
    tradition: 'hermetic',
    duration: 20,
    frequency: 'Quotidienne',
    instructions: [
      'S\'asseoir en position méditative',
      'Contempler un principe hermétique',
      'Observer ses manifestations dans la vie',
      'Intégrer la compréhension',
    ],
    benefits: ['Sagesse ancienne', 'Harmonie universelle', 'Transformation'],
    isFavorite: true,
  },
];

// ============================================
// PHILOSOPHIES
// ============================================

export const philosophies = [
  { 
    id: 'compound', 
    name: 'Effet Cumulé', 
    author: 'Darren Hardy',
    description: 'Petites actions quotidiennes = résultats exponentiels',
    color: '#10b981'
  },
  { 
    id: 'atomic', 
    name: 'Habitudes Atomiques', 
    author: 'James Clear',
    description: '1% d\'amélioration chaque jour',
    color: '#3b82f6'
  },
  { 
    id: 'jim-rohn', 
    name: 'Jim Rohn', 
    author: 'Jim Rohn',
    description: 'Tu es la moyenne des 5 personnes que tu fréquentes',
    color: '#f59e0b'
  },
  { 
    id: 'neville', 
    name: 'Imagination Créatrice', 
    author: 'Neville Goddard',
    description: 'L\'imagination crée la réalité',
    color: '#8b5cf6'
  },
];

// ============================================
// UI HELPERS
// ============================================

export const resourceTypeIcons = {
  book: BookOpen,
  video: Video,
  audio: Headphones,
  article: FileText,
  course: Zap,
};

export const statusColors = {
  'to-read': '#64748b',
  'reading': '#3b82f6',
  'completed': '#10b981',
  'to-watch': '#64748b',
  'watching': '#f59e0b',
  'to-listen': '#64748b',
  'listening': '#ec4899',
  'to-explore': '#64748b',
  'exploring': '#8b5cf6',
  'integrated': '#10b981',
};

// ============================================
// MODALS EXPORTS (stubs pour compilation)
// ============================================

export const HABIT_ICONS = ['🎯', '💪', '📚', '🧠', '❤️', '💰', '🧘', '🎨'];
export const HABIT_COLORS = ['#ef4444', '#f97316', '#f59e0b', '#10b981', '#06b6d4', '#3b82f6', '#8b5cf6', '#ec4899'];

export const CATEGORY_LABELS: Record<HabitCategory, string> = {
  health: 'Santé',
  mind: 'Esprit',
  productivity: 'Productivité',
  learning: 'Apprentissage',
  relationships: 'Relations',
  finance: 'Finance',
  spirit: 'Spiritualité',
  creativity: 'Créativité',
};

export const CATEGORY_ICONS: Record<HabitCategory, string> = {
  health: '❤️',
  mind: '🧠',
  productivity: '⚡',
  learning: '📚',
  relationships: '👥',
  finance: '💰',
  spirit: '✨',
  creativity: '🎨',
};

export const CATEGORY_COLORS: Record<HabitCategory, { bg: string; border: string }> = {
  health: { bg: 'bg-red-500/20', border: 'border-red-500/40' },
  mind: { bg: 'bg-purple-500/20', border: 'border-purple-500/40' },
  productivity: { bg: 'bg-amber-500/20', border: 'border-amber-500/40' },
  learning: { bg: 'bg-blue-500/20', border: 'border-blue-500/40' },
  relationships: { bg: 'bg-pink-500/20', border: 'border-pink-500/40' },
  finance: { bg: 'bg-emerald-500/20', border: 'border-emerald-500/40' },
  spirit: { bg: 'bg-indigo-500/20', border: 'border-indigo-500/40' },
  creativity: { bg: 'bg-orange-500/20', border: 'border-orange-500/40' },
};

export const ROUTINE_TEMPLATES = {
  morning: {
    id: 'morning-5am',
    title: 'Routine 5AM',
    name: 'Routine 5AM',
    description: 'Morning routine pour maximiser la journée',
    steps: [
      { title: 'Hydratation', duration: 2, icon: '💧' },
      { title: 'Méditation', duration: 15, icon: '🧘' },
      { title: 'Journaling', duration: 20, icon: '✍️' },
      { title: 'Exercice', duration: 30, icon: '🏃' },
    ],
  },
  evening: {
    id: 'evening-winddown',
    title: 'Evening Wind-Down',
    name: 'Evening Wind-Down',
    description: 'Routine soir pour un sommeil optimal',
    steps: [
      { title: 'Review journée', duration: 10, icon: '📝' },
      { title: 'Gratitude', duration: 5, icon: '🙏' },
      { title: 'Lecture', duration: 20, icon: '📖' },
      { title: 'Digital Detox', duration: 10, icon: '📵' },
    ],
  },
};

export const XP_LEVELS = [
  { level: 1, xp: 0, xpRequired: 0, title: 'Débutant' },
  { level: 2, xp: 100, xpRequired: 100, title: 'Apprenti' },
  { level: 3, xp: 250, xpRequired: 250, title: 'Intermédiaire' },
  { level: 4, xp: 500, xpRequired: 500, title: 'Avancé' },
  { level: 5, xp: 1000, xpRequired: 1000, title: 'Expert' },
  { level: 6, xp: 2000, xpRequired: 2000, title: 'Maître' },
  { level: 7, xp: 5000, xpRequired: 5000, title: 'Légende' },
];
